#!/bin/bash
source ./tools/.slurm
TORCHFT_MANAGER_PORT=29512 \
    TORCHFT_LIGHTHOUSE="http://localhost:29510" \
    torchrun \
    --master_port=29501 \
    --nnodes=1:2  \
    --node_rank=1 \
    --nproc_per_node=1 \
    --max-restarts=3 \
    --rdzv-id=asdsddsded \
    --rdzv-backend=c10d \
    --rdzv-endpoint=localhost \
    ./train_ddp.py
